# Generated by Django 4.1.7 on 2023-05-20 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='actores')),
                ('anio_nacimiento', models.IntegerField(default=None)),
                ('resumen_bibliografico', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='directores')),
                ('anio_nacimiento', models.IntegerField(default=None)),
                ('resumen_bibliografico', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=15)),
                ('contrasenia', models.CharField(max_length=20)),
                ('rol', models.CharField(choices=[('USUARIO', 'Usuario'), ('ADMINISTRADOR', 'Administrador')], default='USUARIO', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_pelicula', models.IntegerField(default=None)),
                ('nombre', models.CharField(max_length=70)),
                ('resumen', models.CharField(max_length=1000)),
                ('categoria', models.CharField(choices=[('ACCION', 'Accion'), ('COMEDIA', 'Comedia'), ('DRAMA', 'Drama'), ('AVENTURA', 'Aventura'), ('TERROR', 'Terror'), ('CIENCIA FICCION', 'Ciencia ficción')], default=None, max_length=20)),
                ('actores', models.ManyToManyField(to='pagina_web.actor')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina_web.director')),
            ],
        ),
    ]
