# Generated by Django 4.1.7 on 2023-05-31 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_peliculas/'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='categoria',
            field=models.CharField(choices=[('ACCION', 'Accion'), ('COMEDIA', 'Comedia'), ('DRAMA', 'Drama'), ('AVENTURA', 'Aventura'), ('TERROR', 'Terror'), ('CIENCIA FICCION', 'Ciencia ficción')], default='ACCION', max_length=20),
        ),
        migrations.CreateModel(
            name='Critica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critica', models.CharField(max_length=1000)),
                ('valoracion', models.IntegerField(default=None)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina_web.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina_web.usuario')),
            ],
        ),
    ]
