# Generated by Django 4.1.7 on 2023-06-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0002_pelicula_foto_alter_pelicula_categoria_critica'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='puntaje',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='critica',
            name='usuario',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
