# Generated by Django 4.1.7 on 2023-06-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0004_alter_pelicula_puntaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='puntaje',
            field=models.IntegerField(null=True),
        ),
    ]
