# Generated by Django 4.1.7 on 2023-06-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0005_alter_pelicula_puntaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='puntaje',
        ),
    ]
