# Generated by Django 4.1.7 on 2023-06-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0006_remove_pelicula_puntaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='puntaje',
            field=models.IntegerField(default=None),
        ),
    ]
