# Generated by Django 4.1.7 on 2023-07-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0007_pelicula_puntaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='critica',
            name='estado',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
