# Generated by Django 4.1.7 on 2023-07-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0008_critica_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='critica',
            old_name='valoracion',
            new_name='puntaje',
        ),
        migrations.RemoveField(
            model_name='critica',
            name='usuario',
        ),
        migrations.AddField(
            model_name='critica',
            name='correo',
            field=models.CharField(default='None', max_length=35),
        ),
        migrations.AddField(
            model_name='critica',
            name='nombre',
            field=models.CharField(default='None', max_length=70),
        ),
    ]
