# Generated by Django 4.1.7 on 2023-07-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0009_rename_valoracion_critica_puntaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='resumen_bibliografico',
            field=models.CharField(max_length=3000),
        ),
    ]
