# Generated by Django 4.1.7 on 2023-07-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0012_alter_pelicula_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critica',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
