# Generated by Django 4.1.7 on 2023-07-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0013_alter_critica_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critica',
            name='estado',
            field=models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=9),
        ),
    ]
